name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os:
        - macOS-latest
        - ubuntu-20.04
        - windows-2019
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    # --- Linux
    - name: Install Dependencies (Linux)
      if: startsWith(matrix.os, 'ubuntu-')
      run: sudo apt update && sudo apt install libpcap-dev libcurl4-openssl-dev
    # --- Windows
    - uses: seanmiddleditch/gha-setup-vsdevenv@8c6bbf80998779f2bba87b1452832e561b65fd57
      if: startsWith(matrix.os, 'windows-')
    - uses: rinsuki/setup-swift-windows@master
      if: startsWith(matrix.os, 'windows-')
      with:
        version: "5.4.2"
    # --- Shared
    - name: Run Test
      run: swift test
